name: ssg_scrapper

on:
  schedule:
    - cron: '0 5 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4
        pip install requests
        
      
    - name: Run!
      run: python main.py

    - name: push
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        FOLDER: /
      run: |
        apt-get update && \
        apt-get install -y git && \
        cd $GITHUB_WORKSPACE && \
        git init && \
        git config --global user.email "${COMMIT_EMAIL}" && \
        git config --global user.name "${COMMIT_NAME}" && \
        REPOSITORY_PATH="https://${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" && \
        if [ -z "$BASE_BRANCH" ]
        then
          BASE_BRANCH="main"
        fi
        git checkout $BASE_BRANCH && \
        git add .
        git commit -m "$BASE_BRANCH 에 deploy - $(date +"%T")" && \
        git push
      shell: bash
